[package]
name = "minimal"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
bevy = { workspace = true }
bevy_frame_capture = { path = "../../crates/bevy_frame_capture"}
log = { workspace = true }
pretty_env_logger = { workspace = true }
