[package]
name = "bevy_remote_asset"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
bevy.workspace = true 
pin-project = "1.1.3"
surf = {version = "2.3", default-features = false, features = ["h1-client-rustls"]}