[package]
name = "minimal"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
bevy.workspace = true
bevy_headless = { path = "../../crates/bevy_headless"}
log.workspace = true
pretty_env_logger.workspace = true
